test: Try again

diff --git a/.github/workflows/automated_integration_test.yml b/.github/workflows/automated_integration_test.yml
--- a/.github/workflows/automated_integration_test.yml
+++ b/.github/workflows/automated_integration_test.yml
@@ -260,20 +260,36 @@ jobs:
             disable-animations: false
             script: echo "Generated AVD snapshot for caching."
 
-      - name: 🚀 Integration tests on Android Emualator
+      # - name: 🚀 Integration tests on Android Emualator
+      #   uses: reactivecircus/android-emulator-runner@v2
+      #   with:
+      #       api-level: ${{ matrix.api-level }}
+      #       force-avd-creation: false
+      #       # arch: ${{ matrix.arch }}
+      #       emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
+      #       disable-animations: true
+      #       script: |
+      #           cd /opt/android/cake_wallet/
+      #           cd scripts/android/ && sudo./app_env.sh cakewallet && ./app_config.sh && cd ../.. && ./model_generator.sh
+      #           flutter pub get
+      #           flutter drive --driver=test_driver/integration_test.dart --target=integration_test/test_suites/
+      #           if [ $? -ne 0 ]; then
+      #           echo "Tests failed"
+      #           exit 1
+      #           fi
+      - name: 🚀 Integration tests on Android Emulator
         uses: reactivecircus/android-emulator-runner@v2
         with:
             api-level: ${{ matrix.api-level }}
             force-avd-creation: false
-            # arch: ${{ matrix.arch }}
             emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
             disable-animations: true
             script: |
-                cd /opt/android/cake_wallet/
-                cd scripts/android/ && sudo ./app_env.sh cakewallet && ./app_config.sh && cd ../.. && ./model_generator.sh
+                cd /opt/android/cake_wallet
                 flutter pub get
                 flutter drive --driver=test_driver/integration_test.dart --target=integration_test/test_suites/
                 if [ $? -ne 0 ]; then
-                echo "Tests failed"
-                exit 1
+                  echo "Tests failed"
+                  exit 1
                 fi
+              
